import {
  ArrowLeftRight,
  Briefcase,
  Building2,
  CalendarCheck2,
  CalendarDays,
  Flag,
  Footprints,
  Hourglass,
  History,
  Lock,
  MapPin,
  PartyPopper,
  Sun,
  TrendingDown,
  TrendingUp,
  type LucideIcon,
} from "lucide-react";

export const STAT_ICONS: Record<string, LucideIcon> = {
  total: CalendarDays,
  nacionales: Flag,
  regionales: MapPin,
  comunales: Building2,
  restantes: Hourglass,
  transcurridos: History,
  irrenunciables: Lock,
  domingos: Sun,
  entreSemana: Briefcase,
  mesMax: TrendingUp,
  mesMin: TrendingDown,
  gapMax: ArrowLeftRight,
  gapMin: ArrowLeftRight,
  finesLargos: PartyPopper,
  puente: Footprints,
  lunes: CalendarCheck2,
  viernes: CalendarCheck2,
  sabado: CalendarCheck2,
  domingo: CalendarCheck2,
};
